// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYsYlEXyA2AQ4xhx0uKRifWpBaUk91pGU',
    appId: '1:245106255438:web:7e96819982aefe16e1c51f',
    messagingSenderId: '245106255438',
    projectId: 'fila-facil-a7282',
    authDomain: 'fila-facil-a7282.firebaseapp.com',
    storageBucket: 'fila-facil-a7282.firebasestorage.app',
    measurementId: 'G-HMWKCJWZ38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZ6S8vMfc4KvC3tkvTSdSK_vZL3lxWqw',
    appId: '1:245106255438:android:073f76331487e339e1c51f',
    messagingSenderId: '245106255438',
    projectId: 'fila-facil-a7282',
    storageBucket: 'fila-facil-a7282.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjy52UmPjtMV00O7so8P_TfEr-gspuNZA',
    appId: '1:245106255438:ios:7b2ee2a5d547d17be1c51f',
    messagingSenderId: '245106255438',
    projectId: 'fila-facil-a7282',
    storageBucket: 'fila-facil-a7282.firebasestorage.app',
    androidClientId: '245106255438-7h00b85glm42vsv3oa3qfkol20nikmsf.apps.googleusercontent.com',
    iosClientId: '245106255438-e4tsldbo22cvsdarmc5kd7f3rhfo0rq5.apps.googleusercontent.com',
    iosBundleId: 'com.ufba.mobilefilafacil',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjy52UmPjtMV00O7so8P_TfEr-gspuNZA',
    appId: '1:245106255438:ios:7b2ee2a5d547d17be1c51f',
    messagingSenderId: '245106255438',
    projectId: 'fila-facil-a7282',
    storageBucket: 'fila-facil-a7282.firebasestorage.app',
    androidClientId: '245106255438-7h00b85glm42vsv3oa3qfkol20nikmsf.apps.googleusercontent.com',
    iosClientId: '245106255438-e4tsldbo22cvsdarmc5kd7f3rhfo0rq5.apps.googleusercontent.com',
    iosBundleId: 'com.ufba.mobilefilafacil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYsYlEXyA2AQ4xhx0uKRifWpBaUk91pGU',
    appId: '1:245106255438:web:97e5567b813aa850e1c51f',
    messagingSenderId: '245106255438',
    projectId: 'fila-facil-a7282',
    authDomain: 'fila-facil-a7282.firebaseapp.com',
    storageBucket: 'fila-facil-a7282.firebasestorage.app',
    measurementId: 'G-6PKZG8GC3Z',
  );
}
